config {
  type: "table",
  schema: "dash01_staging",
  description: "AAT_SESSIONS"
}

select
  date,
	landingpagepath,
  devicecategory,
  split(sourcemedium,"/")[offset(0)] source,
  split(sourcemedium,"/")[offset(1)] medium,
  hostname,
  campaign,
  browser,
  channelgrouping,

  sessions,
  bounces,
  sessionduration,
  pageviews,
  transactions,
  transactionrevenue,
  goal1completions,
  goal2completions,
  goal7completions,
  goal13completions

from
  ${ref("AAT_GA_SESSIONS_01")}