config {
  type: "table",
  schema: "dash01_analyses",
  tags: ["tests"]
}

with output as
(select 
  shoppingstage, 
  sum(sessions) output_aat_shopping_behaviour
from ${ref("aat_shopping_behaviour")}
group by shoppingstage
),

input as
(select 
  shoppingstage, 
  sum(sessions) source_aat_shopping_behaviour
from ${ref("AAT_GA_SHOPPING_BEHAVIOUR_01")}
group by shoppingstage
)

select * 
from input
full join output
using (shoppingstage)
order by shoppingstage

